inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - "app/controllers/evmbaselines_controller.rb"

Rails/ApplicationRecord:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/*"

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/DotPosition:
   EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Proc:
  Exclude:
    - "app/models/evmbaseline.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "init.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 100
